### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Stratus3D** [drunomics/syncd#5]
This looks exactly like what I need. I'm going to be using something like this in development, since I need to sync with a development server. The lack of activity on this PR is a little concerning though. Is this project still actively maintained?

**Comment by dkebler** [comment]
@Stratus3D.  Looks like the owner is AWOL but I've been using it for awhile now.  It's so simple (just two scripts) that one can fork and modify it easily (like I did for local sync).  I use it to mirror a copy of a data partition to a USB drive and to do development on raspberry pi's by syncing code on my dev computer to the RPi for running.   Easy to invoke at startup.   The watch script uses inotify.  https://techarena51.com/index.php/inotify-tools-example/

**Comment by Stratus3D** [comment]
@dkebler Thanks for comment. That's an interest use case for this. I ended up not using syncd, but if I ever have a need for it in the future I will use it. Thanks!

**Comment by fago** [comment]
Yes, the project is not part of our actively used infrastructure any more, so it's not maintained very actively. However I'm happy to accept PRs that improve the project.
